config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#splash'
  devise_for :users
  resources :home, :only => [:splash, :index]
  resources :profiles
  resources :hicoos do
    resources :comments, :only => [:new, :create, :update, :delete]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :hicoos

  validates_uniqueness_of :user_name, :case_sensitive => false

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => ":style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_attached_file :cover, :styles => { :large => "1300x400!", :thumb => "250x77!" }, :default_url => ":style/cover_default.jpg"

  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update(profile_params)
      redirect_to profile_path(@profile)
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:user_name, :user_id, :avatar, :file, :file_file_name, :file_content_type, :file_file_size, :file_updated_at, :hi_quote_one, :hi_quote_two, :hi_quote_three, :bio)
  end

end

app/views/profiles/edit.html.erb
<h2>Edit <%= @profile.user_name %></h2>

    <%= form_for @profile do |f| %>

    <div class="form-group">
      <%= f.label :avatar  %>
      <%= f.file_field :avatar %>
    </div>

    <div class="form-group">
      <%= f.label :cover_photo %>
      <%= f.file_field :cover %>
    </div>

    <div class="form-group">
      <%= f.label :bio  %>
      <%= f.text_area :bio, autofocus: true, class: 'form-control'  %>
    </div>

    <div class="form-group">
      <%= f.label :user_name  %>
      <%= f.text_field :user_name, autofocus: true, class: 'form-control'  %>
    </div>

    <div class="form-group">
      <p>Your Hi-Quote does not have to be <em>strictly</em> haiku format, but the closer the better. This is so you can use traditional styling if you would like.</p>
      <%= f.label :hi_quote_line_one  %>
      <%= f.text_area :hi_quote_one, autofocus: true, class: 'form-control'  %>
      <%= f.label :hi_quote_line_two  %>
      <%= f.text_area :hi_quote_two, autofocus: true, class: 'form-control'  %>
      <%= f.label :hi_quote_line_three  %>
      <%= f.text_area :hi_quote_three, autofocus: true, class: 'form-control'  %>
    </div>

    <div class="form-group">
      <%= f.submit "Update", class: "btn btn-primary" %>
    </div>

    <% end %>

    <%= link_to "Back", :back %>

app/views/profiles/index.html.erb
<% if @profiles.any? %>
  <% @profiles.each do |profile| %>
    <h3><%= link_to profile.user_name, profile_path(profile) %></h3>
  <% end %>
<% end %>

app/views/profiles/show.html.erb
<div class="profile-banner">
  <%= image_tag(@profile.cover(:large), :class => 'profile-cover') %>
  <div class="profile-pic-div">
    <%= image_tag(@profile.avatar(:medium), :class => 'profile-pic') %>
  </div>
</div>


<div class="profile-container">

  <!-- Profile side -->
  <div class="profile-box well">
    <% if current_user.id == @profile.user_id %>
    <h1>Welcome, <%= current_user.profile.user_name %>!</h1>

    <br>
    <%= link_to "Edit your profile", edit_profile_path(@profile) %>
    <% else %>

    <h1><%= @profile.user_name %>'s Profile</h1>

    <% end %>
    <p>Poet since <%= @profile.created_at.strftime("%Y-%m-%d") %></p>
    <h2><%= @profile.user_name %>'s Hi Quote</h2>
    <div class="inner">
      <h4>"<%= @profile.hi_quote_one %></h4>
      <h4><%= @profile.hi_quote_two %></h4>
      <h4><%= @profile.hi_quote_three %>"</h4>
    </div>
  </div>
<!-- Coo side -->
  <div class="profile-coo">
    <% if @profile.hicoos.any? %>
    <% @profile.hicoos.each do |coo| %>
    <div class="well">
      <%= link_to profile_path(coo.profile) do %>
      <div class="right">
        <h4><%= coo.author %></h4>
        <%= image_tag(coo.profile.avatar(:thumb)) %>
        <br>
        <% if current_user.profile.id == coo.profile_id %>
        <%= link_to "Edit your Hi Coo", edit_hicoo_path(coo) %>
        <% end %>
      </div>
      <% end %>
      <% if coo.pic? %>
        <%= image_tag(coo.pic(:medium)) %>
      <% end %>
      <h3><%= coo.title %></h3>
      <h2><%= coo.line_one %></h2>
      <h2><%= coo.line_two %></h2>
      <h2><%= coo.line_three %></h2>
      <br>
      <p><%= coo.created_at.strftime("%Y-%m-%d") %></p>
      <hr>
      <div class="row">
        <ul class="list-inline mini-list-nav">
          <ul class="list-unstyled col-xs-3">
            <li><%= link_to 'Comment', new_hicoo_comment_path(coo.id), id: 'comment_link_button', remote: true %>
                <% if coo.comments.any? %>
                  <li><%= coo.comments.length %></li>
                <% else %>
                  <li>0</li>
                <% end %>
            </li>
          </ul>
          <ul class="list-unstyled col-xs-3">
            <li><%= link_to 'Like' %>
    <!-- insert if similar to above for 'likes' here             -->
                  <li>0</li>

            </li>
          </ul>
          <ul class="list-unstyled col-xs-3">
            <li><%= link_to 'Not Sure Yet' %>
    <!-- insert if similar to above for 'likes' here             -->
                  <li>0</li>

            </li>
          </ul>
        </ul>
      </div>
    </div>
    <% end %>
    <% else %>
      <h3>This poet has not recorded any Coo yet.</h3>
    <% end %>
  </div>
  <div class="twit-embed-profile">
    <a class="twitter-timeline"  href="https://twitter.com/hashtag/haikuchallenge" data-widget-id="890633974938128384">#haikuchallenge Tweets</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

  </div>
</div>