config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#splash'
  devise_for :users
  resources :home, :only => [:splash, :index]
  resources :profiles
  resources :hicoos do
    resources :comments, :only => [:new, :create, :update, :delete]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user
      @profile = current_user.profile
    end
    @hicoos = Hicoo.all

  end
end

app/views/home/index.html.erb
<br>
<!-- Mini profile display -->
<div class="col-xs-3">
  <% if current_user %>
  <div class="panel panel-default panel-profile">
    <div class="panel-heading pro-heading"></div>
    <div class="panel-body pro-body text-center">
      <%= image_tag(@profile.avatar(:thumb), :class => "panel-profile-img") %>
      <h5 class="panel-title"><%= @profile.user_name %></h5>
      <br>
      <p class="bio">"<%= @profile.hi_quote_one %></p>
      <p class="bio"><%= @profile.hi_quote_two %></p>
      <p class="bio"><%= @profile.hi_quote_three %>"</p>
      <hr>
      <ul class="list-inline mini-list-pro">
        <ul class="list-unstyled col-xs-3">
          <li>Coo
             <li><%= @profile.hicoos.length %></li>
          </li>
        </ul>
        <ul class="list-unstyled col-xs-3">
          <li>Something
             <li><%= @profile.hicoos.length %></li>
          </li>
        </ul>
      </ul>
    </div>
  </div>
  <% else %>
  <div class="panel panel-default panel-profile ">
    <div class="panel-heading pro-heading"></div>
    <div class="panel-body pro-body text-center">
      <%= image_tag('thumb/missing.png', :class => "panel-profile-img") %>
      <h5 class="panel-title">Not logged in</h5>
      <br>
      <p class="bio">"You can see from there</p>
      <p class="bio">but you cannot make Hi-coo</p>
      <p class="bio">shouldn't you sign in?"</p>
      <hr>
      <ul class="list-inline mini-list-pro">
        <ul class="list-unstyled col-xs-3">
          <li>
            <%= link_to 'Sign In', new_user_session_path %>
          </li>
        </ul>
        <ul class="list-unstyled col-xs-3">
          <li>
             <%= link_to 'Sign Up', new_user_registration_path %>
          </li>
        </ul>
      </ul>
    </div>
  </div>
  <% end %>
</div>

<!-- Main hi coo display -->
<div class="col-xs-6 main-coo-col">
  <% if current_user %>
    <div class="main-page-post-header well">
      <%= image_tag(@profile.avatar(:thumb), :class => "round-image-30 left") %>
      <h4>Would you like to Coo?</h4>
      <%= link_to 'Coo', new_hicoo_path(), id: "new_coo", remote: true %>
    </div>
  <% end %>
  <div class="main-page-coo-reload well">
    <h6 class='home-refresh'><%= link_to 'Find new Coo', home_index_path %></h6>
  </div>
  <% if @hicoos.any? %>
    <% @hicoos.each do |coo| %>
      <div class="well">
        <%= link_to profile_path(coo.profile) do %>
        <div class="mini-header">
          <%= image_tag(coo.profile.avatar(:thumb), :class => "round-image-50 left") %>
          <h5><%= coo.author %></h5>
        </div>
        <% end %>
        <%= link_to hicoo_path(coo) do %>
        <div class="mini-coo-box">
          <% if coo.pic? %>
            <%= image_tag(coo.pic(:medium)) %>
          <% end %>
          <h5><%= coo.title %></h5>
          <h4><%= coo.line_one %></h4>
          <h4><%= coo.line_two %></h4>
          <h4><%= coo.line_three %></h4>
        </div>
        <% end %>
        <p><%= coo.created_at.strftime("%Y-%m-%d") %></p>
        <hr>
  <!-- mini comment/like display -->
        <div class="row">
          <ul class="list-inline mini-list-nav">
            <ul class="list-unstyled col-xs-3">
              <li><%= link_to 'Comment', new_hicoo_comment_path(coo.id), id: 'comment_link_button', remote: true %>
                  <% if coo.comments.any? %>
                    <li><%= coo.comments.length %></li>
                  <% else %>
                    <li>0</li>
                  <% end %>
              </li>
            </ul>
            <ul class="list-unstyled col-xs-3">
              <li><%= link_to 'Like' %>
      <!-- insert if similar to above for 'likes' here             -->
                    <li>0</li>

              </li>
            </ul>
            <ul class="list-unstyled col-xs-3">
              <li><%= link_to 'Not Sure Yet' %>
      <!-- insert if similar to above for 'likes' here             -->
                    <li>0</li>

              </li>
            </ul>
          </ul>
        </div>

      </div>
    <% end %>
  <% end %>
</div>

<!-- Embedded twitter -->
<div class="col-xs-3">
  <a class="twitter-timeline"  href="https://twitter.com/hashtag/haiku" data-widget-id="890020578039549952">#haiku Tweets</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>

app/views/home/index.js.erb
// $(document).ready(function(){
//
//   $('.home-refresh').click(function() {
//       location.reload(true);
//   });
// });

app/views/home/splash.html.erb
<div class="splash-header">
  <h1>Hi-Coo</h1>
</div>
<div class="splash-body">
  <h1 class="splash-line-1">Little birds on the wire </h1>
  <h1 class="splash-line-2">Tell the world your every thought</h1>
  <h1 class="splash-line-3">It must be Hi-coo</h1>
  <br>

  <% if current_user %>
    <h2>Welcome! <%= link_to 'Home', home_index_path %></h2>
  <% else %>
    <h2><%= link_to 'Enter', home_index_path %></h2>
  <% end %>
  <br>
  <br>
  <br>
  <%= image_tag('white-birds.jpg', :class => "bottom-birds") %>
</div>