config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#splash'
  devise_for :users
  resources :home, :only => [:splash, :index]
  resources :profiles
  resources :hicoos do
    resources :comments, :only => [:new, :create, :update, :delete]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HiCoo</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Ceviche+One|Hammersmith+One|Satisfy" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <h1 class='headline'><%= link_to 'Hi Coo!', '/' %></h1>
      <ul class="nav navbar-nav navbar-left">
        <li>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Search</button>
          </form>
        </li>
        <% if current_user && current_user.admin %>
          <li><%= link_to 'Admin', rails_admin_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", home_index_path %></li>
          <% if current_user %>
          <li><%= link_to 'All Poets', profiles_path %></li>
          <li><%= link_to 'My Profile', profile_path(current_user.id) %></li>

          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
      </ul>
    </div>
    <div class="container main">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <%= yield %>
    </div>

  </body>
</html>